name: dart_server
description: Dart Web Server.
author: Mars <578595193@qq.com>
homepage: https://github.com/dart-server/dart-server
version: 0.0.1
dependencies:
  body_parser: any
  angel_route: ^3.0.6